# MICROSERVIZI FE
services:
  frontend:
    container_name: web
    restart: on-failure
    env_file:
      - environments/.env.local
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - net
