# MICROSERVIZI FE
services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ./environment/.env.local
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ..:/app
