# MICROSERVIZI FE
services:
  frontend:
    build: ../
    env_file:
      - ./environment/.env.local
    ports:
      - "80:80"
    environment:
      API_GATEWAY_URL: ${API_GATEWAY_URL}
    networks:
      - net