version: '3.8'

# MICROSERVIZI BE
services:
  gateway-service:
    build: ./GatewayService
    env_file:
      - ./docker/environment/be-local.env
    environment:
      BE_HOST_DB: ${BE_HOST_DB:-jdbc:postgresql://db:5432/library}
      BE_USER_DB: ${BE_USER_DB:-library}
      BE_PASSWORD_DB: ${BE_PASSWORD_DB:-library}
    ports:
      - "8083:8080"
    depends_on:
      keycloak:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://gateway-service:8080/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net

  administrator-service:
    build: ./AdministratorService
    env_file:
      - ./docker/environment/be-local.env
    environment:
      BE_HOST_DB: ${BE_HOST_DB:-jdbc:postgresql://db:5432/library}
      BE_USER_DB: ${BE_USER_DB:-library}
      BE_PASSWORD_DB: ${BE_PASSWORD_DB:-library}
    ports:
      - "8084:8080"
    depends_on:
      gateway-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8080/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net

  library-service:
    build: ./LibraryService
    env_file:
      - ./docker/environment/be-local.env
    environment:
      BE_HOST_DB: ${BE_HOST_DB:-jdbc:postgresql://db:5432/library}
      BE_USER_DB: ${BE_USER_DB:-library}
      BE_PASSWORD_DB: ${BE_PASSWORD_DB:-library}
    ports:
      - "8085:8080"
    volumes:
      - ./docker/storage/img:/app/thumbnails
    depends_on:
      gateway-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8080/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net