logging:
  level:
    org.springframework: info
    org.springframework.security: ${LOG_LEVEL:info}
    org.springframework.oauth2: ${LOG_LEVEL:info}
    org.springframework.web: ${LOG_LEVEL:info}



spring:
  # Sicurezza
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  flyway:
    default-schema: library
    driver-class-name: org.postgresql.Driver
    url: ${LIBRARY_URL_DB}
    user: ${LIBRARY_USER_DB}
    password: ${LIBRARY_PASSWORD_DB}

  # Database
  datasource:
    url: ${LIBRARY_URL_DB}
    username: ${LIBRARY_USER_DB}
    password: ${LIBRARY_PASSWORD_DB}
    driver-class-name: org.postgresql.Driver
  # JPA
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true


