include:
  - ../backend/docker/docker-compose-be-local.yml
  - ../frontend/docker/docker-compose-fe-local.yml

services:
  db:
    image: postgis/postgis
    platform: linux/amd64
    restart: on-failure
    env_file:
      - ./environments/.env.local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./locale/database/data:/var/lib/postgresql/data #persistenza dati
      - ./locale/database/init:/docker-entrypoint-initdb.d #script di inizializzazione
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net

  keycloak:
    image: keycloak/keycloak:latest
    restart: on-failure
    env_file:
      - ./environments/.env.local
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      # IMPOSTAZIONI DB
      KC_DB: ${POSTGRES_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      # METRICHE
      KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED}
      KC_METRICS_ENABLED: ${KC_METRICS_ENABLED}

      KC_HOSTNAME_URL: http://localhost:4200
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY_HEADERS: xforwarded
    ports:
      - "${KC_PORT}:8080"
    volumes:
      - ./locale/keycloak/realm/data:/opt/keycloak/data/import
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "{ printf 'HEAD /health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net
    command:
      - start-dev
      - --import-realm

  geoserver:
    image: docker.osgeo.org/geoserver:2.28.0
    platform: linux/amd64
    restart: on-failure
    env_file:
      - ./environments/.env.local
    environment:
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
      POSTGRES_JNDI_ENABLED: true
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./locale/geoserver/data_dir:/opt/geoserver_data/
    ports:
      - "${GEOSERVER_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net

networks:
  net:
    driver: bridge