# MICROSERVIZI BE
services:
  gateway:
    build:
      context: ..
      dockerfile: GatewayService/Dockerfile
    restart: on-failure
    env_file:
      - environments/.env.local
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SHARED_DATA_LOGS: /temp/logs
    ports:
      - "${GATEWAY_PORT}:8083"
    volumes:
      - ${SHARED_DATA_LOGS}:/temp/logs:rw
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8083/social-library/actuator/health | grep '\"status\":\"UP\"' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - net

  administrator:
    build:
      context: ..
      dockerfile: AdministratorService/Dockerfile
    restart: on-failure
    env_file:
      - ./environments/.env.local
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      ADMINISTRATOR_URL_DB: ${ADMINISTRATOR_URL_DB}
      ADMINISTRATOR_USER_DB: ${ADMINISTRATOR_USER_DB}
      ADMINISTRATOR_PASSWORD_DB: ${ADMINISTRATOR_PASSWORD_DB}
      SHARED_DATA_LOGS: /temp/logs
    ports:
      - "${ADMINISTRATOR_PORT}:8084"
    volumes:
      - ${SHARED_DATA_LOGS}:/temp/logs:rw
    depends_on:
      gateway:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8084/api/administrator/actuator/health | grep '\"status\":\"UP\"' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - net

  library:
    build:
      context: ..
      dockerfile: LibraryService/Dockerfile
    restart: on-failure
    env_file:
      - ./environments/.env.local
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      LIBRARY_URL_DB: ${LIBRARY_URL_DB}
      LIBRARY_USER_DB: ${LIBRARY_USER_DB}
      LIBRARY_PASSWORD_DB: ${LIBRARY_PASSWORD_DB}
      SHARED_DATA_LOGS: /temp/logs
    ports:
      - "${LIBRARY_PORT}:8085"
    volumes:
      - ${SHARED_DATA_THUMBNAILS}:/app/thumbnails:rw
      - ${SHARED_DATA_LOGS}:/temp/logs:rw
    depends_on:
      gateway:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8085/api/library/actuator/health | grep '\"status\":\"UP\"' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - net