# MICROSERVIZI BE
services:
  gateway:
    build: ../GatewayService
    env_file:
      - environment/be-local.env
    environment:
      GATEWAY_HOST_DB: ${GATEWAY_HOST_DB:-jdbc:postgresql://db:5432/library}
      GATEWAY_USER_DB: ${GATEWAY_USER_DB:-library}
      GATEWAY_PASSWORD_DB: ${GATEWAY_PASSWORD_DB:-library}
    ports:
      - "8083:8080"
    depends_on:
      keycloak:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8080/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net

  administrator:
    build: ../AdministratorService
    env_file:
      - environment/be-local.env
    environment:
      ADMINISTRATOR_HOST_DB: ${ADMINISTRATOR_HOST_DB:-jdbc:postgresql://db:5432/library}
      ADMINISTRATOR_USER_DB: ${ADMINISTRATOR_USER_DB:-library}
      ADMINISTRATOR_PASSWORD_DB: ${ADMINISTRATOR_PASSWORD_DB:-library}
    ports:
      - "8084:8080"
    depends_on:
      gateway:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8080/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net

  library:
    build: ../LibraryService
    env_file:
      - environment/be-local.env
    environment:
      LIBRARY_HOST_DB: ${LIBRARY_HOST_DB:-jdbc:postgresql://db:5432/library}
      LIBRARY_USER_DB: ${LIBRARY_USER_DB:-library}
      LIBRARY_PASSWORD_DB: ${LIBRARY_PASSWORD_DB:-library}
      SHARED_DATA_THUMBNAILS: ${SHARED_DATA_THUMBNAILS-./docker/storage/thumbnails}
    ports:
      - "8085:8080"
    volumes:
      - ${SHARED_DATA_THUMBNAILS-./docker/storage/thumbnails}:/app/thumbnails:rw
    depends_on:
      gateway:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8080/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net