logging:
  level:
    org.springframework: info
    org.springframework.security: ${LOG_LEVEL:info}
    org.springframework.oauth2: ${LOG_LEVEL:info}
    org.springframework.web: ${LOG_LEVEL:info}



spring:
  # Database
  datasource:
    url: ${ADMINISTRATOR_URL_DB}
    username: ${ADMINISTRATOR_USER_DB}
    password: ${ADMINISTRATOR_PASSWORD_DB}
    driver-class-name: org.postgresql.Driver
  # Flyway
  flyway:
    default-schema: administrator
    driver-class-name: org.postgresql.Driver
    url: ${ADMINISTRATOR_URL_DB}
    user: ${ADMINISTRATOR_USER_DB}
    password: ${ADMINISTRATOR_PASSWORD_DB}

  # Sicurezza
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  # JPA
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true


